# Generated by Django 2.2.3 on 2019-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author_Q',
            field=models.CharField(max_length=20),
        ),
    ]
