# Generated by Django 2.2.3 on 2019-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190914_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author_A',
            field=models.CharField(max_length=20),
        ),
    ]
