# Generated by Django 2.2.3 on 2019-09-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
