# Generated by Django 2.2.3 on 2019-09-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20190925_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.CharField(default='Web Development', max_length=50),
            preserve_default=False,
        ),
    ]
