# Generated by Django 2.2.3 on 2019-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutYou',
            field=models.CharField(default='None', max_length=150),
            preserve_default=False,
        ),
    ]
