# Generated by Django 2.2.3 on 2019-09-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_profile_aboutyou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutYou',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
